
let nome = ''

try {
    console.log(nome)
    throw "O nome n√£o pode ser VAZIO"
}

catch (err) {
    console.log(`Houve um erro: ${err}`)
}


console.log('boa noite!')


